apiVersion: v1
kind: Service
metadata:
  name: order-service  # Nama layanan yang akan dibuat
  namespace: e-commerce  # Namespace di mana layanan ini akan berada
  labels:
    app: order-app  # Label yang diterapkan ke layanan ini
spec:
  selector:
    app: order-app  # Selector yang akan mencocokkan pod yang akan dilayani oleh layanan ini
  ports:
  - port: 3000  # Port yang akan di-ekspos oleh layanan ini
    name: http  # Nama port, dalam hal ini "http"
  type: NodePort  # Tipe layanan, dalam hal ini "NodePort"
